// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvVi02Hl_T0h34lcJoyrgr1r6Jk0_wPXU',
    appId: '1:499876695765:web:e1898f7c2aef4ca2a0dc5c',
    messagingSenderId: '499876695765',
    projectId: 'help-vrywhere',
    authDomain: 'help-vrywhere.firebaseapp.com',
    storageBucket: 'help-vrywhere.firebasestorage.app',
    measurementId: 'G-3JMN44ZJYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3gubsTV9htxGRof54um4ar9h7yqsoONc',
    appId: '1:499876695765:android:9e4eadd355608804a0dc5c',
    messagingSenderId: '499876695765',
    projectId: 'help-vrywhere',
    storageBucket: 'help-vrywhere.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtMreVwqTK7dNJJPqhowNg7ggKGbtuTC0',
    appId: '1:499876695765:ios:9150cf6a1dee6a2aa0dc5c',
    messagingSenderId: '499876695765',
    projectId: 'help-vrywhere',
    storageBucket: 'help-vrywhere.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationHelpvrywhere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtMreVwqTK7dNJJPqhowNg7ggKGbtuTC0',
    appId: '1:499876695765:ios:9150cf6a1dee6a2aa0dc5c',
    messagingSenderId: '499876695765',
    projectId: 'help-vrywhere',
    storageBucket: 'help-vrywhere.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationHelpvrywhere',
  );
}
